// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCl65b_SCjkkUEtdRfRdLiTelqsQgF6MAo',
    appId: '1:819284969310:web:7e5a300ee89b4f4bd7f1cf',
    messagingSenderId: '819284969310',
    projectId: 'weather-app-20242310',
    authDomain: 'weather-app-20242310.firebaseapp.com',
    storageBucket: 'weather-app-20242310.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9l0H89_sMXJ9DTMZvPRid-2Z9Qm4aJjE',
    appId: '1:819284969310:android:be49cc7d67d12a2fd7f1cf',
    messagingSenderId: '819284969310',
    projectId: 'weather-app-20242310',
    storageBucket: 'weather-app-20242310.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvXe38bmsMzN0ikLjhiIuoagjY4mTTiow',
    appId: '1:819284969310:ios:272f3bcb587d096bd7f1cf',
    messagingSenderId: '819284969310',
    projectId: 'weather-app-20242310',
    storageBucket: 'weather-app-20242310.appspot.com',
    androidClientId: '819284969310-cgh0msb415q4t94p1n9qami12f8pe1fi.apps.googleusercontent.com',
    iosClientId: '819284969310-3qphphoef5bvfsf1jdlkp4ivdclm10s5.apps.googleusercontent.com',
    iosBundleId: 'com.example.wheatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvXe38bmsMzN0ikLjhiIuoagjY4mTTiow',
    appId: '1:819284969310:ios:272f3bcb587d096bd7f1cf',
    messagingSenderId: '819284969310',
    projectId: 'weather-app-20242310',
    storageBucket: 'weather-app-20242310.appspot.com',
    androidClientId: '819284969310-cgh0msb415q4t94p1n9qami12f8pe1fi.apps.googleusercontent.com',
    iosClientId: '819284969310-3qphphoef5bvfsf1jdlkp4ivdclm10s5.apps.googleusercontent.com',
    iosBundleId: 'com.example.wheatherApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCl65b_SCjkkUEtdRfRdLiTelqsQgF6MAo',
    appId: '1:819284969310:web:38a6a12d28f73a50d7f1cf',
    messagingSenderId: '819284969310',
    projectId: 'weather-app-20242310',
    authDomain: 'weather-app-20242310.firebaseapp.com',
    storageBucket: 'weather-app-20242310.appspot.com',
  );

}